spring.application.name=hrm-security

spring.datasource.url=jdbc:postgresql://localhost:5432/medical_db1
spring.datasource.username=postgres
spring.datasource.password=123456
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=9a4f2c8d3e1b7f6a5c4d3b2a1e0f9b8a7c6d5e4f3a2b1c0e9d8c7b6a5f4e3d2c
jwt.expiration=86400000

cloudinary.cloud-name=mzbvhydx
cloudinary.api-key=462521792674982
cloudinary.api-secret=8wAnBizyAg0WJ37q2z2DsyTqSUA 

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=taitbt3124@gmail.com
spring.mail.password=kxuv fmhy ddat intz
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true